spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

github:
  client:
    id: Iv1.2d15475aa762bf73
    secret: 8977e98dd4de1cd94b1e24f9e51d75aee3162660
  redirect:
    uri: http://localhost:8080/callback
